"""Sequential phase module specs."""

from __future__ import annotations

from .types import PhaseModuleSpec

# Runner functions live in core.module_runners to keep this module focused on
# metadata and spec definitions.
from core.module_runners import (  # noqa: E402, F401
    _run_account_takeover,
    _run_ai_analysis,
    _run_api_injection,
    _run_api_scan,
    _run_graphql_audit,
    _run_auth_bypass,
    _run_autopwn_postprocess,
    _run_business_logic,
    _run_chain_analysis,
    _run_cloud_storage,
    _run_cmdi_postprocess,
    _run_cookie_hsts_hook,
    _run_cors,
    _run_crawl_discovery,
    _run_credential_spray,
    _run_csrf_exploit,
    _run_csrf_hook,
    _run_csp_bypass_hook,
    _run_deduplicate_results,
    _run_deserialization,
    _run_email_harvest,
    _run_file_upload,
    _run_findings_json,
    _run_forbidden_bypass,
    _run_fuzzer_discovery,
    _run_guaranteed_checks,
    _run_har_analysis,
    _run_header_inject,
    _run_headless_discovery,
    _run_html_report,
    _run_json_report,
    _run_jwt_scan,
    _run_lfi_postprocess,
    _run_markdown_report,
    _run_normalize_findings,
    _run_open_redirect,
    _run_osint,
    _run_param_discovery,
    _run_passive_hook,
    _run_payload_report,
    _run_poc_generation,
    _run_proto_pollution,
    _run_race_condition,
    _run_recon,
    _run_sarif_report,
    _run_scan_summary,
    _run_secrets_hook,
    _run_severity_summary,
    _run_smuggling,
    _run_sqli_postprocess,
    _run_ssrf_postprocess,
    _run_subdomain_scan,
    _run_subdomain_takeover,
    _run_tech_intel,
    _run_wordlist_generation,
    _run_xss_postprocess,
    _run_sploitus_search,
    _run_brute_force,
    _run_scan_history,
    _run_google_dorker,
    _run_wayback_harvester,
    _run_urlscan_passive,
    _run_osint_identity,
    _run_osint_breach,
    _run_osint_sector,
    _run_container_registry,
    _run_cicd_exposure,
    _run_nuclei,
    _run_asset_search,
    _run_git_history,
)


PHASE_MODULES = (
    PhaseModuleSpec(
        id="guaranteed",
        option_key=None,
        name="Guaranteed Security Checks",
        phase="pre_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_guaranteed_checks,
    ),
    PhaseModuleSpec(
        id="recon",
        option_key=None,
        name="Recon",
        phase="pre_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_recon,
    ),
    PhaseModuleSpec(
        id="osint",
        option_key="osint",
        name="OSINT",
        phase="pre_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_osint,
    ),
    PhaseModuleSpec(
        id="tech",
        option_key="tech",
        name="Technology Intel",
        phase="pre_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_tech_intel,
    ),
    PhaseModuleSpec(
        id="sploitus",
        option_key="tech", # Tie Sploitus Search to the tech flag
        name="Sploitus Exploit Search",
        phase="pre_scan",
        requires_forms=False,
        collect_results=False, # sploitus search just prints enrichments to screen for now
        runner=_run_sploitus_search,
    ),
    PhaseModuleSpec(
        id="brute",
        option_key="brute", # We'll need to add a --brute flag later or tie it to something
        name="SSH/FTP Brute-Force",
        phase="pre_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_brute_force,
    ),
    PhaseModuleSpec(
        id="dorking",
        option_key="dorking",
        name="Google Dorking",
        phase="pre_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_google_dorker,
    ),
    PhaseModuleSpec(
        id="wayback",
        option_key="wayback",
        name="Wayback Machine Harvest",
        phase="pre_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_wayback_harvester,
    ),
    PhaseModuleSpec(
        id="urlscan",
        option_key="urlscan",
        name="URLScan.io Passive Recon",
        phase="pre_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_urlscan_passive,
    ),
    PhaseModuleSpec(
        id="osint_identity",
        option_key="osint",
        name="OSINT Identity/SSO Mapping",
        phase="pre_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_osint_identity,
    ),
    PhaseModuleSpec(
        id="osint_breach",
        option_key="osint",
        name="OSINT Breach Intelligence",
        phase="pre_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_osint_breach,
    ),
    PhaseModuleSpec(
        id="osint_sector",
        option_key="osint",
        name="OSINT Sector-Specific Recon",
        phase="pre_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_osint_sector,
    ),
    PhaseModuleSpec(
        id="container_registry",
        option_key="cloud",
        name="Container Registry Leak Detection",
        phase="pre_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_container_registry,
    ),
    PhaseModuleSpec(
        id="cicd_exposure",
        option_key="cloud",
        name="CI/CD Platform Exposure",
        phase="pre_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_cicd_exposure,
    ),
    PhaseModuleSpec(
        id="asset_search",
        option_key="asset_search",
        name="Multi-Provider Asset Search (Censys/ZoomEye/FOFA/Onyphe/Netlas/FullHunt/LeakIX)",
        phase="pre_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_asset_search,
    ),
    PhaseModuleSpec(
        id="nuclei",
        option_key="nuclei",
        name="Nuclei Community Templates",
        phase="pre_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_nuclei,
    ),
    PhaseModuleSpec(
        id="git_history",
        option_key="git_history",
        name="Git History Secret Scanner (white-box + exposed-.git probe)",
        phase="pre_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_git_history,
    ),
    PhaseModuleSpec(
        id="cloud",
        option_key="cloud",
        name="Cloud Storage",
        phase="phase4_target",
        requires_forms=False,
        collect_results=True,
        runner=_run_cloud_storage,
    ),
    PhaseModuleSpec(
        id="takeover",
        option_key="takeover",
        name="Subdomain Takeover",
        phase="phase4_target",
        requires_forms=False,
        collect_results=True,
        runner=_run_subdomain_takeover,
    ),
    PhaseModuleSpec(
        id="api_scan",
        option_key="api_scan",
        name="API Scan",
        phase="phase4_target",
        requires_forms=False,
        collect_results=True,
        runner=_run_api_scan,
    ),
    PhaseModuleSpec(
        id="subdomain",
        option_key="subdomain",
        name="Subdomain Discovery",
        phase="phase4_target",
        requires_forms=False,
        collect_results=False,
        runner=_run_subdomain_scan,
    ),
    PhaseModuleSpec(
        id="cors",
        option_key="cors",
        name="CORS",
        phase="target_checks",
        requires_forms=False,
        collect_results=True,
        runner=_run_cors,
    ),
    PhaseModuleSpec(
        id="header_inject",
        option_key="header_inject",
        name="Header Injection",
        phase="target_checks",
        requires_forms=False,
        collect_results=True,
        runner=_run_header_inject,
    ),
    PhaseModuleSpec(
        id="fuzz",
        option_key="fuzz",
        name="Endpoint Fuzzer",
        phase="discovery_seed",
        requires_forms=False,
        collect_results=False,
        runner=_run_fuzzer_discovery,
    ),
    PhaseModuleSpec(
        id="headless",
        option_key="headless",
        name="Headless Discovery",
        phase="discovery_expand",
        requires_forms=False,
        collect_results=False,
        runner=_run_headless_discovery,
    ),
    PhaseModuleSpec(
        id="param_discovery",
        option_key=None,
        name="Hidden Parameter Discovery",
        phase="discovery_expand",
        requires_forms=False,
        collect_results=False,
        runner=_run_param_discovery,
    ),
    PhaseModuleSpec(
        id="crawl",
        option_key="crawl",
        name="Crawler Discovery",
        phase="discovery_expand",
        requires_forms=False,
        collect_results=False,
        runner=_run_crawl_discovery,
    ),
    PhaseModuleSpec(
        id="passive",
        option_key="passive",
        name="Passive Scan",
        phase="page_hooks",
        requires_forms=False,
        collect_results=True,
        runner=_run_passive_hook,
    ),
    PhaseModuleSpec(
        id="secrets",
        option_key="secrets",
        name="Secrets Scan",
        phase="page_hooks",
        requires_forms=False,
        collect_results=True,
        runner=_run_secrets_hook,
    ),
    PhaseModuleSpec(
        id="csrf",
        option_key="csrf",
        name="CSRF",
        phase="page_hooks",
        requires_forms=True,
        collect_results=True,
        runner=_run_csrf_hook,
    ),
    PhaseModuleSpec(
        id="csp_bypass",
        option_key="passive",
        name="CSP Bypass",
        phase="page_hooks",
        requires_forms=False,
        collect_results=True,
        runner=_run_csp_bypass_hook,
    ),
    PhaseModuleSpec(
        id="cookie_hsts",
        option_key="passive",
        name="Cookie & HSTS Audit",
        phase="page_hooks",
        requires_forms=False,
        collect_results=True,
        runner=_run_cookie_hsts_hook,
    ),
    PhaseModuleSpec(
        id="xss_postprocess",
        option_key="xss",
        name="XSS Postprocess",
        phase="result_processors",
        requires_forms=False,
        collect_results=False,
        runner=_run_xss_postprocess,
    ),
    PhaseModuleSpec(
        id="csrf_exploit",
        option_key="csrf",
        name="CSRF Exploit",
        phase="result_processors",
        requires_forms=False,
        collect_results=False,
        runner=_run_csrf_exploit,
    ),
    PhaseModuleSpec(
        id="sqli_postprocess",
        option_key="sqli",
        name="SQLi Postprocess",
        phase="result_processors",
        requires_forms=False,
        collect_results=True,
        runner=_run_sqli_postprocess,
    ),
    PhaseModuleSpec(
        id="cmdi_postprocess",
        option_key="cmdi",
        name="CMDi Postprocess",
        phase="result_processors",
        requires_forms=False,
        collect_results=False,
        runner=_run_cmdi_postprocess,
    ),
    PhaseModuleSpec(
        id="autopwn_postprocess",
        option_key="exploit",
        name="Auto-Pwn Bridge",
        phase="result_processors",
        requires_forms=False,
        collect_results=False,
        runner=_run_autopwn_postprocess,
    ),
    PhaseModuleSpec(
        id="lfi_postprocess",
        option_key="exploit",
        name="LFI Auto-Exploit",
        phase="result_processors",
        requires_forms=False,
        collect_results=False,
        runner=_run_lfi_postprocess,
    ),
    PhaseModuleSpec(
        id="ssrf_postprocess",
        option_key="exploit",
        name="SSRF Cloud Probe",
        phase="result_processors",
        requires_forms=False,
        collect_results=False,
        runner=_run_ssrf_postprocess,
    ),
    PhaseModuleSpec(
        id="api_injection",
        option_key=None,
        name="API Body Injection",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_api_injection,
    ),
    PhaseModuleSpec(
        id="har_analysis",
        option_key="har_output",
        name="HAR Analysis",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_har_analysis,
    ),
    PhaseModuleSpec(
        id="graphql_audit",
        option_key=None,
        name="GraphQL Deep Audit",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_graphql_audit,
    ),
    PhaseModuleSpec(
        id="redirect",
        option_key="redirect",
        name="Open Redirect",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_open_redirect,
    ),
    PhaseModuleSpec(
        id="spray",
        option_key="spray",
        name="Credential Spray",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_credential_spray,
    ),
    PhaseModuleSpec(
        id="email",
        option_key="email",
        name="Email Harvest",
        phase="post_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_email_harvest,
    ),
    PhaseModuleSpec(
        id="wordlist",
        option_key="wordlist",
        name="Wordlist Generation",
        phase="post_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_wordlist_generation,
    ),
    PhaseModuleSpec(
        id="jwt",
        option_key="jwt",
        name="JWT",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_jwt_scan,
    ),
    PhaseModuleSpec(
        id="race",
        option_key="race",
        name="Race Condition",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_race_condition,
    ),
    PhaseModuleSpec(
        id="smuggle",
        option_key="smuggle",
        name="HTTP Smuggling",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_smuggling,
    ),
    PhaseModuleSpec(
        id="proto",
        option_key="proto",
        name="Prototype Pollution",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_proto_pollution,
    ),
    PhaseModuleSpec(
        id="deser",
        option_key="deser",
        name="Deserialization",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_deserialization,
    ),
    PhaseModuleSpec(
        id="bizlogic",
        option_key="bizlogic",
        name="Business Logic",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_business_logic,
    ),
    PhaseModuleSpec(
        id="chain",
        option_key="chain",
        name="Chain Analysis",
        phase="post_scan",
        requires_forms=False,
        collect_results=False,
        runner=_run_chain_analysis,
    ),
    PhaseModuleSpec(
        id="forbidden_bypass",
        option_key="forbidden_bypass",
        name="403/401 Bypass",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_forbidden_bypass,
    ),
    PhaseModuleSpec(
        id="file_upload",
        option_key="file_upload",
        name="File Upload",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_file_upload,
    ),
    PhaseModuleSpec(
        id="ato",
        option_key="ato",
        name="Account Takeover",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_account_takeover,
    ),
    PhaseModuleSpec(
        id="auth_bypass",
        option_key="auth_bypass",
        name="2FA & Auth Bypass",
        phase="post_scan",
        requires_forms=False,
        collect_results=True,
        runner=_run_auth_bypass,
    ),
    PhaseModuleSpec(
        id="dedupe",
        option_key=None,
        name="Deduplicate Findings",
        phase="result_cleanup",
        requires_forms=False,
        collect_results=False,
        runner=_run_deduplicate_results,
    ),
    PhaseModuleSpec(
        id="ai_analysis",
        option_key="ai",
        name="AI Analysis",
        phase="analysis",
        requires_forms=False,
        collect_results=False,
        runner=_run_ai_analysis,
    ),
    PhaseModuleSpec(
        id="summary",
        option_key=None,
        name="Summary",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_scan_summary,
    ),
    PhaseModuleSpec(
        id="scan_history",
        option_key="history",
        name="Scan Drift Detection",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_scan_history,
    ),
    PhaseModuleSpec(
        id="html_report",
        option_key="html",
        name="HTML Report",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_html_report,
    ),
    PhaseModuleSpec(
        id="payload_report",
        option_key=None,
        name="Payload Report",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_payload_report,
    ),
    PhaseModuleSpec(
        id="markdown_report",
        option_key=None,
        name="Markdown Report",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_markdown_report,
    ),
    PhaseModuleSpec(
        id="poc_generation",
        option_key=None,
        name="PoC Generation",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_poc_generation,
    ),
    PhaseModuleSpec(
        id="normalize_findings",
        option_key=None,
        name="Normalize Findings",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_normalize_findings,
    ),
    PhaseModuleSpec(
        id="json_report",
        option_key=None,
        name="JSON Report",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_json_report,
    ),
    PhaseModuleSpec(
        id="sarif_report",
        option_key="sarif",
        name="SARIF Report",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_sarif_report,
    ),
    PhaseModuleSpec(
        id="findings_json",
        option_key=None,
        name="Enhanced Findings JSON",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_findings_json,
    ),
    PhaseModuleSpec(
        id="severity_summary",
        option_key=None,
        name="Severity Summary",
        phase="reporting",
        requires_forms=False,
        collect_results=False,
        runner=_run_severity_summary,
    ),
)
