"""Tests for the new Interactsh / Collaborator OOB providers in utils/oob."""

from __future__ import annotations

import os
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from utils.oob import (
    CollaboratorProvider,
    InteractshProvider,
    OOBClient,
)


pytestmark = pytest.mark.unit


def _json_response(payload, *, raises_json: bool = False):
    if raises_json:
        return SimpleNamespace(json=lambda: (_ for _ in ()).throw(ValueError("bad")))
    return SimpleNamespace(json=lambda: payload)


# ── InteractshProvider ──────────────────────────────────────────────────────


def test_interactsh_host_uses_correlation_id():
    provider = InteractshProvider(server="oast.fun", correlation_id="abc123")
    assert provider.get_host() == "abc123.oast.fun"


def test_interactsh_correlation_id_autogenerated_when_omitted():
    provider = InteractshProvider(server="oast.fun")
    assert len(provider.correlation_id) == 33
    assert provider.correlation_id.isalnum()


def test_interactsh_poll_parses_interactions():
    payload = {
        "data": [
            {
                "protocol": "http",
                "full-id": "atoken123.abc.oast.fun",
                "remote-address": "1.2.3.4",
            },
            {
                "protocol": "dns",
                "full-id": "btoken.abc.oast.fun",
            },
        ]
    }
    fake_get = lambda url, timeout: _json_response(payload)  # noqa: E731
    provider = InteractshProvider(
        server="oast.fun", correlation_id="abc", http_get=fake_get
    )
    interactions = provider.poll()
    assert {i.token for i in interactions} == {"atoken123", "btoken"}
    assert {i.type for i in interactions} == {"http", "dns"}


def test_interactsh_poll_handles_network_failure():
    def boom(url, timeout):
        raise RuntimeError("connection refused")

    provider = InteractshProvider(
        server="oast.fun", correlation_id="abc", http_get=boom
    )
    assert provider.poll() == []


def test_interactsh_poll_handles_malformed_json():
    fake_get = lambda url, timeout: _json_response(None, raises_json=True)  # noqa: E731
    provider = InteractshProvider(
        server="oast.fun", correlation_id="abc", http_get=fake_get
    )
    assert provider.poll() == []


# ── CollaboratorProvider ────────────────────────────────────────────────────


def test_collaborator_inert_without_env(monkeypatch):
    monkeypatch.delenv("BURP_COLLAB_SERVER", raising=False)
    monkeypatch.delenv("BURP_COLLAB_KEY", raising=False)
    provider = CollaboratorProvider()
    assert provider.get_host() == ""
    assert provider.poll() == []


def test_collaborator_get_host_includes_server(monkeypatch):
    provider = CollaboratorProvider(server="collab.example", biid="K")
    host = provider.get_host()
    assert host.endswith(".collab.example")
    assert len(host.split(".")[0]) == 12


def test_collaborator_poll_parses_responses():
    payload = {
        "responses": [
            {
                "interactionString": "tok1",
                "protocol": "http",
            },
            {"interactionString": "tok2", "protocol": "dns"},
        ]
    }
    fake_get = lambda url, timeout: _json_response(payload)  # noqa: E731
    provider = CollaboratorProvider(
        server="collab.example", biid="K", http_get=fake_get
    )
    interactions = provider.poll()
    assert {i.token for i in interactions} == {"tok1", "tok2"}


def test_collaborator_poll_url_carries_biid():
    captured: dict = {}

    def capturing(url, timeout):
        captured["url"] = url
        return _json_response({"responses": []})

    provider = CollaboratorProvider(
        server="collab.example", biid="MY-KEY", http_get=capturing
    )
    provider.poll()
    assert "biid=MY-KEY" in captured["url"]


# ── OOBClient dispatch ──────────────────────────────────────────────────────


def test_oobclient_local_mode_unchanged():
    """Local mode still works after the multi-provider expansion."""
    c = OOBClient(mode="local")
    assert c.mode == "local"


def test_oobclient_interactsh_mode_uses_provider():
    c = OOBClient(mode="interactsh", server="oast.fun", correlation_id="abc")
    assert isinstance(c.provider, InteractshProvider)
    assert c.provider.correlation_id == "abc"


def test_oobclient_collaborator_mode_uses_provider():
    c = OOBClient(mode="collab", server="collab.example", biid="K")
    assert isinstance(c.provider, CollaboratorProvider)
    # Alias 'collaborator' also accepted.
    c2 = OOBClient(mode="collaborator", server="collab.example", biid="K")
    assert isinstance(c2.provider, CollaboratorProvider)


def test_oobclient_unknown_mode_raises():
    with pytest.raises(ValueError):
        OOBClient(mode="webhook-xyz")
