"""
Tests for utils/waf.py — WAF fingerprint detection
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.waf import WAFDetector


class TestWAFDetector:
    """Tests for WAF fingerprinting engine."""

    def setup_method(self):
        """Create fresh detector for each test."""
        self.detector = WAFDetector()

    def test_fingerprint_count(self):
        assert len(self.detector.fingerprints) >= 20, (
            f"Only {len(self.detector.fingerprints)} fingerprints, need 20+"
        )

    def test_detect_cloudflare_header(self):
        detector = WAFDetector()
        headers = {"server": "cloudflare", "cf-ray": "abc123"}
        result = detector.analyze_response(headers, "")
        assert result == "Cloudflare"

    def test_detect_akamai_header(self):
        detector = WAFDetector()
        headers = {"server": "AkamaiGHost"}
        result = detector.analyze_response(headers, "")
        assert result == "Akamai"

    def test_detect_imperva_cookie(self):
        detector = WAFDetector()
        headers = {"set-cookie": "visid_incap_12345=abc; path=/"}
        result = detector.analyze_response(headers, "")
        assert result == "Imperva / Incapsula"

    def test_detect_wordfence_text(self):
        detector = WAFDetector()
        headers = {}
        body = "Your access to this site has been limited by the site owner"
        result = detector.analyze_response(headers, body)
        assert result == "Wordfence"

    def test_detect_modsecurity_text(self):
        detector = WAFDetector()
        headers = {}
        body = "This error was generated by Mod_Security"
        result = detector.analyze_response(headers, body)
        assert result == "ModSecurity"

    def test_detect_aws_waf(self):
        detector = WAFDetector()
        headers = {"x-amzn-errortype": "ForbiddenException"}
        result = detector.analyze_response(headers, "")
        assert result == "AWS WAF"

    def test_detect_azure_front_door(self):
        detector = WAFDetector()
        headers = {"x-azure-ref": "abc123ref"}
        result = detector.analyze_response(headers, "")
        assert result == "Azure Front Door"

    def test_detect_sucuri_text(self):
        detector = WAFDetector()
        headers = {}
        body = "Access denied - Sucuri Website Firewall"
        result = detector.analyze_response(headers, body)
        assert result == "Sucuri"

    def test_no_waf_detected(self):
        detector = WAFDetector()
        headers = {"server": "nginx", "content-type": "text/html"}
        body = "Hello world"
        result = detector.analyze_response(headers, body)
        assert result is None

    def test_caches_first_detection(self):
        """Once a WAF is detected, subsequent calls return the cached result."""
        headers1 = {"server": "cloudflare", "cf-ray": "abc"}
        result1 = self.detector.analyze_response(headers1, "")
        assert result1 == "Cloudflare"

        # Even with different headers, cached result returned
        headers2 = {"server": "nginx"}
        result2 = self.detector.analyze_response(headers2, "")
        assert result2 == "Cloudflare"

    def test_all_fingerprints_have_detection_method(self):
        """Every fingerprint must have at least one detection method."""
        for name, sigs in self.detector.fingerprints.items():
            has_headers = bool(sigs.get("headers"))
            has_cookies = bool(sigs.get("cookies"))
            has_text = bool(sigs.get("text"))
            assert has_headers or has_cookies or has_text, (
                f"WAF '{name}' has no detection signatures"
            )
