"""
cyberm4fia-scanner - WAF Fingerprinting
Detects Web Application Firewalls and applies evasion delays
Supports 20+ WAF vendors with header, cookie, and body text signatures
"""

import threading


class WAFDetector:
    def __init__(self):
        self.lock = threading.Lock()
        self.detected_waf = None
        self.fingerprints = {
            # ── CDN / Cloud WAFs ──
            "Cloudflare": {
                "headers": {"server": "cloudflare", "cf-ray": ""},
                "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
                "text": ["attention required! | cloudflare", "cf-error-details"],
            },
            "Akamai": {
                "headers": {"server": "akamaighost", "x-akamai-transformed": ""},
                "cookies": ["akacl", "ak_bmsc", "bm_sv", "akamai_generated"],
            },
            "AWS WAF": {
                "headers": {"x-amzn-errortype": "", "x-amzn-requestid": ""},
                "cookies": ["awselb", "awsalb", "aws-waf-token"],
                "text": ["request blocked", "automated queries"],
            },
            "Azure Front Door": {
                "headers": {"x-azure-ref": "", "x-fd-healthprobe": ""},
                "cookies": ["afd_session"],
                "text": ["azure front door"],
            },
            "Azure App Gateway": {
                "headers": {"server": "microsoft-azure-application-gateway"},
                "cookies": ["ApplicationGatewayAffinity"],
            },
            "Google Cloud Armor": {
                "headers": {"server": "gws", "x-goog-": ""},
                "text": ["our systems have detected unusual traffic"],
            },
            # ── Enterprise WAFs ──
            "Imperva / Incapsula": {
                "headers": {"x-iinfo": "", "x-cdn": "incapsula"},
                "cookies": ["visid_incap", "incap_ses", "nlbi_"],
                "text": ["blocked by incapsula", "incident id", "powered by incapsula"],
            },
            "F5 BIG-IP ASM": {
                "headers": {"server": "bigip", "x-wa-info": ""},
                "cookies": ["bigipserver", "ts", "f5_cspm"],
                "text": ["the requested url was rejected"],
            },
            "Fortinet FortiWeb": {
                "headers": {"server": "fortiweb"},
                "cookies": ["cookiesession1", "fgd_token"],
                "text": ["server unavailable", ".fyi_err_page"],
            },
            "Barracuda WAF": {
                "headers": {"server": "barracuda"},
                "cookies": ["barra_counter_session", "bNVR_"],
                "text": ["you have been blocked", "barracuda"],
            },
            "Citrix NetScaler": {
                "headers": {"via": "ns-cache", "cneonction": "", "x-client-ip": ""},
                "cookies": ["ns_af", "citrix_ns_id", "nsc_"],
                "text": ["ns.zerodelay.net", "citrix transaction id"],
            },
            "Radware AppWall": {
                "headers": {"x-sl-compstate": ""},
                "cookies": ["reese84"],
                "text": ["radware", "unauthorized activity has been detected"],
            },
            # ── ModSecurity / Open Source ──
            "ModSecurity": {
                "headers": {"server": "mod_security", "modsecurity": ""},
                "text": [
                    "modsecurity",
                    "mod_security",
                    "not acceptable",
                    "this error was generated by mod_security",
                    "rules of the mod_security",
                ],
            },
            # ── CMS-Specific WAFs ──
            "Wordfence": {
                "headers": {},
                "text": [
                    "generated by wordfence",
                    "your access to this site has been limited",
                    "wordfence",
                ],
            },
            "Sucuri": {
                "headers": {"x-sucuri-id": "", "server": "sucuri"},
                "cookies": ["sucuri_cloudproxy"],
                "text": [
                    "access denied - sucuri",
                    "sucuri website firewall",
                    "cloudproxy",
                ],
            },
            "SiteLock": {
                "headers": {"x-sitelock": ""},
                "text": ["sitelock incident id", "sitelock"],
            },
            # ── DDoS Protection ──
            "DDoS-Guard": {
                "headers": {"server": "ddos-guard"},
                "cookies": ["__ddg1", "__ddg2"],
                "text": ["ddos-guard"],
            },
            "StackPath": {
                "headers": {"x-sp-waf": "", "server": "stackpath"},
                "cookies": ["sp_waf_sid"],
            },
            "Reblaze": {
                "headers": {"server": "reblaze"},
                "cookies": ["rbzid"],
                "text": ["reblaze"],
            },
            # ── Russian / Asian WAFs ──
            "Qrator": {
                "headers": {"x-qrator-requestid": ""},
                "cookies": ["qrator_ssid"],
            },
            "Wallarm": {
                "headers": {"server": "nginx-wallarm"},
                "text": ["wallarm"],
            },
            # ── Fallback ──
            "Generic WAF": {
                "headers": {
                    "x-fireeye": "",
                    "x-denied-reason": "",
                    "x-wzws-requested-method": "",
                },
                "text": [
                    "access denied",
                    "security policy",
                    "request denied",
                    "web application firewall",
                    "please retry your request",
                    "your request has been blocked",
                ],
            },
        }

    def analyze_response(self, headers, text):
        """Analyze HTTP response to fingerprint WAF vendors."""
        with self.lock:
            if self.detected_waf:
                return self.detected_waf

            headers_lower = {k.lower(): v.lower() for k, v in headers.items()}
            text_lower = text.lower()

            for waf_name, signatures in self.fingerprints.items():
                # Check Headers (key existence for unique keys, value match for common ones)
                for h_key, h_val in signatures.get("headers", {}).items():
                    if h_key in headers_lower:
                        if not h_val:
                            # Empty value = key existence is enough (e.g. x-azure-ref)
                            self.detected_waf = waf_name
                            return waf_name
                        elif h_val in headers_lower[h_key]:
                            # Non-empty value = must match (e.g. server: cloudflare)
                            self.detected_waf = waf_name
                            return waf_name
                # Check Cookies
                if "set-cookie" in headers_lower:
                    for c_sig in signatures.get("cookies", []):
                        if c_sig in headers_lower["set-cookie"]:
                            self.detected_waf = waf_name
                            return waf_name
                # Check Body Text
                for t_sig in signatures.get("text", []):
                    if t_sig in text_lower:
                        self.detected_waf = waf_name
                        return waf_name

            return None


waf_detector = WAFDetector()
