"""
cyberm4fia-scanner - WAF Fingerprinting
Detects Web Application Firewalls and applies evasion delays
Supports 20+ WAF vendors with header, cookie, and body text signatures
"""

import threading


class WAFDetector:
    def __init__(self):
        self.lock = threading.Lock()
        self.detected_waf = None
        self.fingerprints = {
            # ── CDN / Cloud WAFs ──
            "Cloudflare": {
                "headers": {"server": "cloudflare", "cf-ray": ""},
                "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
                "text": ["attention required! | cloudflare", "cf-error-details"],
            },
            "Akamai": {
                "headers": {"server": "akamaighost", "x-akamai-transformed": ""},
                "cookies": ["akacl", "ak_bmsc", "bm_sv", "akamai_generated"],
            },
            "AWS WAF": {
                "headers": {"x-amzn-errortype": "", "x-amzn-requestid": ""},
                "cookies": ["awselb", "awsalb", "aws-waf-token"],
                "text": ["request blocked", "automated queries"],
            },
            "Azure Front Door": {
                "headers": {"x-azure-ref": "", "x-fd-healthprobe": ""},
                "cookies": ["afd_session"],
                "text": ["azure front door"],
            },
            "Azure App Gateway": {
                "headers": {"server": "microsoft-azure-application-gateway"},
                "cookies": ["ApplicationGatewayAffinity"],
            },
            "Google Cloud Armor": {
                "headers": {"server": "gws", "x-goog-": ""},
                "text": ["our systems have detected unusual traffic"],
            },
            # ── Enterprise WAFs ──
            "Imperva / Incapsula": {
                "headers": {"x-iinfo": "", "x-cdn": "incapsula"},
                "cookies": ["visid_incap", "incap_ses", "nlbi_"],
                "text": ["blocked by incapsula", "incident id", "powered by incapsula"],
            },
            "F5 BIG-IP ASM": {
                "headers": {"server": "bigip", "x-wa-info": ""},
                "cookies": ["bigipserver", "ts", "f5_cspm"],
                "text": ["the requested url was rejected"],
            },
            "Fortinet FortiWeb": {
                "headers": {"server": "fortiweb"},
                "cookies": ["cookiesession1", "fgd_token"],
                "text": ["server unavailable", ".fyi_err_page"],
            },
            "Barracuda WAF": {
                "headers": {"server": "barracuda"},
                "cookies": ["barra_counter_session", "bNVR_"],
                "text": ["you have been blocked", "barracuda"],
            },
            "Citrix NetScaler": {
                "headers": {"via": "ns-cache", "cneonction": "", "x-client-ip": ""},
                "cookies": ["ns_af", "citrix_ns_id", "nsc_"],
                "text": ["ns.zerodelay.net", "citrix transaction id"],
            },
            "Radware AppWall": {
                "headers": {"x-sl-compstate": ""},
                "cookies": ["reese84"],
                "text": ["radware", "unauthorized activity has been detected"],
            },
            # ── ModSecurity / Open Source ──
            "ModSecurity": {
                "headers": {"server": "mod_security", "modsecurity": ""},
                "text": [
                    "modsecurity",
                    "mod_security",
                    "not acceptable",
                    "this error was generated by mod_security",
                    "rules of the mod_security",
                ],
            },
            # ── CMS-Specific WAFs ──
            "Wordfence": {
                "headers": {},
                "text": [
                    "generated by wordfence",
                    "your access to this site has been limited",
                    "wordfence",
                ],
            },
            "Sucuri": {
                "headers": {"x-sucuri-id": "", "server": "sucuri"},
                "cookies": ["sucuri_cloudproxy"],
                "text": [
                    "access denied - sucuri",
                    "sucuri website firewall",
                    "cloudproxy",
                ],
            },
            "SiteLock": {
                "headers": {"x-sitelock": ""},
                "text": ["sitelock incident id", "sitelock"],
            },
            # ── DDoS Protection ──
            "DDoS-Guard": {
                "headers": {"server": "ddos-guard"},
                "cookies": ["__ddg1", "__ddg2"],
                "text": ["ddos-guard"],
            },
            "StackPath": {
                "headers": {"x-sp-waf": "", "server": "stackpath"},
                "cookies": ["sp_waf_sid"],
            },
            "Reblaze": {
                "headers": {"server": "reblaze"},
                "cookies": ["rbzid"],
                "text": ["reblaze"],
            },
            # ── Russian / Asian WAFs ──
            "Qrator": {
                "headers": {"x-qrator-requestid": ""},
                "cookies": ["qrator_ssid"],
            },
            "Wallarm": {
                "headers": {"server": "nginx-wallarm"},
                "text": ["wallarm"],
            },
            # ── Fallback ──
            "Generic WAF": {
                "headers": {
                    "x-fireeye": "",
                    "x-denied-reason": "",
                    "x-wzws-requested-method": "",
                },
                "text": [
                    "access denied",
                    "security policy",
                    "request denied",
                    "web application firewall",
                    "please retry your request",
                    "your request has been blocked",
                ],
            },
        }

    # ── WAF-specific tamper recommendations ──
    TAMPER_MAP = {
        "Cloudflare": ["doubleurlencode", "unicodeencode", "randomcase", "multiline"],
        "Akamai": ["doubleurlencode", "charencode", "space2comment", "base64encode"],
        "AWS WAF": ["urlencode", "multiline", "unicodeencode", "space2tab"],
        "Azure Front Door": ["urlencode", "randomcase", "space2comment"],
        "Azure App Gateway": ["urlencode", "randomcase", "space2comment"],
        "Google Cloud Armor": ["doubleurlencode", "unicodeencode", "concat"],
        "Imperva / Incapsula": [
            "charencode",
            "concat",
            "base64encode",
            "space2comment",
        ],
        "F5 BIG-IP ASM": [
            "space2comment",
            "between",
            "commentbeforeparentheses",
            "randomcase",
        ],
        "Fortinet FortiWeb": ["doubleurlencode", "randomcase", "space2tab"],
        "Barracuda WAF": ["urlencode", "space2comment", "randomcase"],
        "Citrix NetScaler": ["space2comment", "urlencode", "charencode"],
        "Radware AppWall": ["doubleurlencode", "unicodeencode", "concat"],
        "ModSecurity": [
            "space2comment",
            "between",
            "commentbeforeparentheses",
            "randomcase",
            "concat",
        ],
        "Wordfence": ["unicodeencode", "htmlencode", "doubleurlencode", "randomcase"],
        "Sucuri": ["doubleurlencode", "charencode", "space2comment", "base64encode"],
        "SiteLock": ["urlencode", "randomcase", "space2comment"],
        "DDoS-Guard": ["urlencode", "randomcase"],
        "StackPath": ["doubleurlencode", "unicodeencode"],
        "Reblaze": ["doubleurlencode", "randomcase", "space2comment"],
        "Qrator": ["urlencode", "randomcase"],
        "Wallarm": ["unicodeencode", "space2comment", "concat", "randomcase"],
        "Generic WAF": ["space2comment", "randomcase", "urlencode", "doubleurlencode"],
    }

    # HTTP status codes that indicate a WAF block
    WAF_BLOCK_CODES = {403, 406, 429, 444, 503}

    def analyze_response(self, headers, text):
        """Analyze HTTP response to fingerprint WAF vendors."""
        with self.lock:
            if self.detected_waf:
                return self.detected_waf

            headers_lower = {k.lower(): v.lower() for k, v in headers.items()}
            text_lower = text.lower()

            for waf_name, signatures in self.fingerprints.items():
                # Check Headers (key existence for unique keys, value match for common ones)
                for h_key, h_val in signatures.get("headers", {}).items():
                    if h_key in headers_lower:
                        if not h_val:
                            self.detected_waf = waf_name
                            return waf_name
                        elif h_val in headers_lower[h_key]:
                            self.detected_waf = waf_name
                            return waf_name
                # Check Cookies
                if "set-cookie" in headers_lower:
                    for c_sig in signatures.get("cookies", []):
                        if c_sig in headers_lower["set-cookie"]:
                            self.detected_waf = waf_name
                            return waf_name
                # Check Body Text
                for t_sig in signatures.get("text", []):
                    if t_sig in text_lower:
                        self.detected_waf = waf_name
                        return waf_name

            return None

    def get_recommended_tampers(self, waf_name: str = None) -> list:
        """Return recommended tamper script names for the detected or given WAF."""
        name = waf_name or self.detected_waf
        if not name:
            return self.TAMPER_MAP.get("Generic WAF", [])
        # Try exact match first, then partial
        if name in self.TAMPER_MAP:
            return self.TAMPER_MAP[name]
        for key, tampers in self.TAMPER_MAP.items():
            if key.lower() in name.lower() or name.lower() in key.lower():
                return tampers
        return self.TAMPER_MAP.get("Generic WAF", [])

    def is_waf_block(self, status_code: int, text: str = "") -> bool:
        """Check if an HTTP response indicates a WAF block."""
        if status_code in self.WAF_BLOCK_CODES:
            return True
        block_phrases = [
            "access denied",
            "blocked",
            "forbidden",
            "not acceptable",
            "request rejected",
            "security policy",
            "waf",
        ]
        text_lower = text.lower()
        return any(phrase in text_lower for phrase in block_phrases)


waf_detector = WAFDetector()
